---
title: "Investigation of Causal Effects"
author: "Daniel Lindner, Simon Witzke"
date: "6/30/2020"
output: pdf_document
---

```{r setup, include=FALSE}
library(xtable)
knitr::opts_chunk$set(tidy.opts=list(width.cutoff=62), tidy=TRUE, message = FALSE, warning = FALSE)
source("./helper.R")
load("./nets/mehra-complete.rda")
load("./nets/-20200702-214850-17500000-built-in.discrete.rds")

# define sample size
sample.size <- 10200

# gather observations from original net
sim.data <- rbn(bn, sample.size)
#sim.data$Year <- as.numeric(as.character(sim.data$Year))

data <- sim.data %>%
  mutate(DateTime = as.numeric(chron(dates = paste(Year, Month, Day, sep="-"), times = paste(Hour, "0", "0", sep=":"), format = c('y-m-d','h:m:s')))) %>%
  filter(!is.na(DateTime)) %>%
  select(-Year, -Month, -Day, -Hour)


test.data <- data %>%
  base::sapply(function(x) if(!is.factor(x)){
    meds <- Ckmedian.1d.dp(x, k=c(2,2))
    trans <- meds$cluster %>%
      base::sapply(function(y) meds$centers[[y]])
    factor(trans)
    } else x) %>%
  base::as.data.frame()

test.data4 <- data %>%
  base::sapply(function(x) if(!is.factor(x)){
    meds <- Ckmedian.1d.dp(x, k=c(5,5))
    trans <- meds$cluster %>%
      base::sapply(function(y) meds$centers[[y]])
    factor(trans)
    } else x) %>%
  base::as.data.frame()


test.data5<- data %>%
  base::sapply(function(x) if(!is.factor(x)){
    meds <- Ckmedian.1d.dp(x, k=c(3,3))
    trans <- meds$cluster %>%
      base::sapply(function(y) meds$centers[[y]])
    factor(trans)
    } else x) %>%
  base::as.data.frame()

test.data7<- data %>%
  base::sapply(function(x) if(!is.factor(x)){
    meds <- Ckmedian.1d.dp(x, k=c(20,20))
    trans <- meds$cluster %>%
      base::sapply(function(y) meds$centers[[y]])
    factor(trans)
    } else x) %>%
  base::as.data.frame()

test.data2 <- discretize(data, breaks=3)

test.data3 <- discretize(data, breaks=2)

test.data6 <- discretize(data, breaks=5)

test.data8 <- discretize(data, breaks=10)
```

## Translation of learned bayesian network to igraph

```{r warning = FALSE}
#sample.size <- 5000000
#sample <- generate.sample(sample.size)

#clustered.data <- sample %>%
# base::sapply(function(x) if(!is.factor(x)){factor(Ckmedian.1d.dp(x, k=c(3,5))$cluster)} else x) %>%
#base::as.data.frame()

# TODO replace bn with our learned and saved model
adj.matrix.from.bngraph <- amat(bn)
adj.matrix.from.learned.graph <- amat(computed.net1)

igraph.from.bnmatrix<- graph_from_adjacency_matrix(adj.matrix.from.bngraph)
igraph.from.learned.graph<- graph_from_adjacency_matrix(adj.matrix.from.learned.graph)


undirected.edges <- get.edge.ids(igraph.from.learned.graph, c("so2","pm10","pm10","so2","so2","co","co","so2", "co","pm10","pm10","co","ssr", "tp","tp","ssr","ws","blh","blh","ws"))

igraph.from.learned.graph <- set.edge.attribute(graph = igraph.from.learned.graph, name = "description", index = undirected.edges, value = "U")


get.edge.ids(igraph.from.learned.graph, c("pm10","so2"))

get.edge.ids(igraph.from.learned.graph, c("so2","pm10"))



edge_attr(igraph.from.learned.graph)

tkplot(igraph.from.learned.graph, vertex.size=35, vertex.label.family="sans", vertex.color="white")
as.numeric(V(igraph.from.learned.graph)["co"])
# TODO mark undirected edges as such

```

## Plot network

```{r pressure, echo=FALSE}
graphviz.plot(bn)
graphviz.plot(computed.net1)
```


## Find causal effect
```{r }
effect.igraph.from.bnmatrix <- causal.effect(y = "so2", x = "co", z = NULL, G = igraph.from.bnmatrix, expr = T)
effect.igraph.from.learned.graph <- causal.effect(y = "t2m", x = "wd", z = NULL, G = igraph.from.learned.graph, expr = T)
effect.igraph.from.learned.graph.inv <- causal.effect(y = "wd", x = "t2m", z = NULL, G = igraph.from.learned.graph, expr = T)
```

$`
```{r echo=FALSE, results="asis"}
cat(effect.igraph.from.learned.graph.inv)
```
`$

## Estimate causal effect strength

```{r results='asis'}
causal.effect.probabilites.so2.co <- function(data) {
  # select relevant columns
  data <- data %>%
    select(so2, co, Type, Zone, DateTime) 
  
  # calculate probabilities for realisations of Zone 
  data <- data %>%
    add_count(Zone) %>%
    mutate(prob_zone = n / n()) %>%
    select(-n) 
  
  # calculate probabilities for realisations of Type 
  data <- data %>%
    add_count(Type) %>%
    mutate(prob_type = n / n()) %>%
    select(-n) 
  
  # calculate probabilities for realisations of Year 
  data <- data %>%
    add_count(DateTime) %>%
    mutate(prob_datetime = n / n()) %>%
    select(-n) 
  
  # calculate conditional probability for so2 by Zone, Type, Year, co
  data <- data %>%
    group_by(Zone, Type, DateTime, co) %>%
    add_count(so2) %>%
    group_by(Zone, Type, DateTime, co) %>%
    mutate(so2_cond_prob = n / n()) %>%
    select(-n) 
  
  # calculate causal effect and add probability for co to table
  data <- data %>%
    ungroup() %>%
    distinct() %>%
    mutate(total_prob = prob_zone * prob_type * prob_datetime * so2_cond_prob) %>%
    group_by(so2, co) %>%
    summarise(P_so2 = sum(total_prob)) %>%
    inner_join(data %>%
                 group_by(co) %>%
                 count(co) %>%
                 mutate(P_co = n / nrow(data)) %>%
                 select(-n))
  
  
}

causal.effect.probabilites.so2.co.simplified <- function(data) {
   data <- data %>%
    select(co, so2) %>%
    distinct() %>%
    mutate(P_so2 = sum(data$co == co & data$so2 == so2)/sum(data$co == co)) %>%
    inner_join(data %>%
                 group_by(co) %>%
                 count(co) %>%
                 mutate(P_co = n / nrow(data)) %>%
                 select(-n))
}

bl <- test.data5 %>%
  select(co, so2) %>%
  unique() %>%
  mutate(p_so2 = do.simplified(test.data5, co, so2))
  

do.simplified <- function(data, co, so2){
  sum(data$co == co & data$so2 == so2)/sum(data$co == co)
}
x.list = c()
y.list = c()
result = c()
for(x in unique(test.data3$co)) {
  for(y in unique(test.data3$so2)) {
    x.list <- append(x.list, x)
    y.list <- append(y.list, y)

    result <- append(result, do.simplified(test.data3, x,y))
  }
}
do.calc.so2.co <- data.frame(co=x.list, so2=y.list, P_so2=result, P_co=c(0.5,0.5,0.5,0.5))
# calculates the conditional mutual information for do(co) on so2
conditional.mutual.information.so2.co <- function(data, calc) {
  #causal.effects <- causal.effect.probabilites.so2.co(data)
  causal.effects <- calc
  
  # Calculation of sum in denominator of logarithm
  log.sum <- function(vj){
    sum(causal.effects %>%
      filter(so2 == vj) %>%
      base::apply(MARGIN = 1, function(x)
      as.numeric(x["P_so2"]) * as.numeric(x["P_co"])))
  }
  
  # Rowwise calculation of Conditional Mutual Information
  sum(causal.effects %>%
        base::apply(MARGIN = 1, function(x)
          as.numeric(x["P_co"]) * as.numeric(x["P_so2"]) * log(as.numeric(x["P_so2"]) / log.sum(x["so2"]))))
}

cep <- conditional.mutual.information.so2.co(test.data3, do.calc.so2.co)


#xtable(causal.effect.probabilites.so2.co(clustered.data), digits = c(0, 0, 0, 10, 5))
#causal.effect.size.so2.co(clustered.data)

MI.co_so2 <- function(data){
  result <- 0
  for (so2 in unique(data$so2)){
    for (co_1 in unique(data$co)){
      joint <- sum(data$so2 == so2 & data$co == co_1)/nrow(data)
      log_counter <-  sum(data$so2 == so2 & data$co == co_1)/sum(data$co == co_1)
      log_denom <- 0
        for(co_2 in unique(data$co)){
            temp_inner <- sum(data$so2 == so2 & data$co == co_2)/nrow(data)
            log_denom <- log_denom + temp_inner
        }
      #print(log_denom)
      temp <- joint*log2(log_counter/log_denom)
      result <- result + if_else(is.nan(temp), 0, temp)
    }
  }
  result
}

mi <- MI.co_so2(test.data3)

xtable(causal.effect.probabilites.so2.co(test.data),
       digits = c(0, 0, 0, 10, 5))
# causal.effect.probabilites.so2.co(test.data)

a <- causal.effect.probabilites.so2.co(test.data3)

a <- causal.effect.probabilites.so2.co.simplified(test.data3)

mi <- conditional.mutual.information.so2.co(test.data3, a)

b <- causal.effect.probabilites.so2.co(test.data2)

conditional.mutual.information.so2.co(test.data2)

cep <- causal.effect.probabilites.so2.co(test.data) %>% arrange(co)

cep %>%
  filter(so2 == 1) %>%
  ggplot(aes(x=co, y = P_co * 100, fill = co)) + geom_bar(stat='identity')

cep %>%
  filter(co == 1) %>%
  ggplot(aes(x=so2, y = P_so2_prior * 100, fill = so2)) + geom_bar(stat='identity')

cep %>%
  ggplot(aes(x=so2, y = P_so2 * 100, fill=co)) + geom_bar(stat='identity', position = position_dodge())

blub <- do.calc.so2.co %>%
  mutate(so2 = factor(so2, levels=c("[-4.62e+05,13.8]", "(13.8,3.33e+05]")), co = as.factor(co))

b <- a %>%
  filter(co == "[-0.983,1.44]")
(plot<-ggplot(a, aes(x=so2, y = P_so2 * 100, fill=co)) + geom_bar(stat='identity', position = position_dodge()) + ylab("P [%]") + ylim(0, 50))

(plot<-ggplot(foo, aes(x=so2, y = P_so2 * 100, fill=co)) + geom_bar(stat='identity', position = position_dodge()) + ylab("P [%]") + ylim(0, 50) + xlab("Sulfur Dioxide (so2)"))

source("helper.R")
save_with_theme(apply_theme(plot))

foo <- test.data3 %>%
  select(co, so2) %>%
  group_by(co) %>%
    add_count(so2) %>%
  group_by(co) %>%
   mutate(P_so2 = n / n()) %>%
    select(-n)  %>%
  unique() %>%
   group_by(so2, co) %>%
    #summarise(so2_cond_prob) %>%
    inner_join(test.data3 %>%
                 group_by(co) %>%
                 count(co) %>%
                 mutate(P_co = n / nrow(data)) %>%
                 select(-n))
  
  



conditional.mutual.information.so2.co(test.data)
library(stringr)

test.data2 %>%
  select(so2) %>%
  distinct() %>%
  mutate(so2_range = as.numeric(str_extract(as.character(so2), "(?<=,)-?[0-9]+(?:.[0-9]+)?(e[\\+\\-][0-9]+)?")) -  as.numeric(str_extract(as.character(so2), "-?[0-9]+(?:.[0-9]+)?(e[\\+\\-][0-9]+)?"))) %>%
  mutate(so2_range_norm = pmax(0.01,scale(so2_range, center = FALSE, scale=sum(so2_range)))) %>%
  inner_join(test.data2 %>%
               count(so2)) %>%
  ggplot(aes(x=so2, y = n, fill = as.character(so2_range), width = so2_range_norm)) + geom_bar(stat='identity') + guides(fill=guide_legend(title="Bin Width")) + ylab("count") + xlab("Sulfur Dioxide (so2)")

test.data2 %>%
  select(co) %>%
  distinct() %>%
  mutate(co_range = as.numeric(str_extract(as.character(co), "(?<=,)-?[0-9]+(?:.[0-9]+)?(e[\\+\\-][0-9]+)?")) -  as.numeric(str_extract(as.character(co), "-?[0-9]+(?:.[0-9]+)?(e[\\+\\-][0-9]+)?"))) %>%
  mutate(co_range_norm = pmax(0.01,scale(co_range, center = FALSE, scale=sum(co_range)))) %>%
  inner_join(test.data2 %>%
               count(co)) %>%
  ggplot(aes(x=co, y = n, fill = as.character(co_range), width = co_range_norm)) + geom_bar(stat='identity') + guides(fill=guide_legend(title="Bin Width")) + ylab("count") + xlab("Carbon Monoxide (co)")



plot <- test.data3 %>%
  select(so2) %>%
  distinct() %>%
  mutate(so2_range = as.numeric(str_extract(as.character(so2), "(?<=,)-?[0-9]+(?:.[0-9]+)?(e[\\+\\-][0-9]+)?")) -  as.numeric(str_extract(as.character(so2), "-?[0-9]+(?:.[0-9]+)?(e[\\+\\-][0-9]+)?"))) %>%
  mutate(so2_range_norm = pmax(0.01,scale(so2_range, center = FALSE, scale=sum(so2_range))))  %>%
  inner_join(test.data3 %>%
               count(so2)) %>%
  ggplot(aes(x=so2, y = n, fill = as.character(round(so2_range,2)), width = so2_range_norm)) + geom_bar(stat='identity') + guides(fill=guide_legend(title="Bin Width")) + ylab("count") + xlab("Sulfur Dioxide (so2)")


plot <- test.data2 %>%
  select(co) %>%
  distinct() %>%
  mutate(co_range = as.numeric(str_extract(as.character(co), "(?<=,)-?[0-9]+(?:.[0-9]+)?(e[\\+\\-][0-9]+)?")) -  as.numeric(str_extract(as.character(co), "-?[0-9]+(?:.[0-9]+)?(e[\\+\\-][0-9]+)?"))) %>%
  mutate(co_range_norm =  pmax(0.01,scale(co_range, center = FALSE, scale=sum(co_range)))) %>%
  inner_join(test.data2%>%
               count(co)) %>%
  ggplot(aes(x=co, y = n, fill = as.character(round(co_range,2)))) + geom_bar(stat='identity') + ylab("count") + xlab("Carbon Monoxide (co)")

plot <- test.data2 %>%
  select(co) %>%
  distinct() %>%
  mutate(co_range = str_extract(as.character(co), "(?<=,)-?[0-9]+(?:.[0-9]+)?(e[\\+\\-][0-9]+)?")) %>%
  inner_join(test.data2%>%
               count(co)) %>%
  ggplot(aes(aes(x=co, y = n, fill = as.character(co_range)))) + geom_bar(stat='identity') + ylab("count") + xlab("Carbon Monoxide (co)") + ylim(0,9000)

plot <- test.data2 %>%
  select(so2) %>%
  distinct() %>%
  mutate(so2_range = str_extract(as.character(so2), "-?[0-9]+(?:.[0-9]+)?(e[\\+\\-][0-9]+)?")) %>%
  inner_join(test.data2%>%
               count(so2)) %>%
  ggplot(aes(x=so2, y = n, fill = as.character(so2_range))) + geom_bar(stat='identity') + ylab("count") + xlab("Sulfur Dioxide (so2)") + ylim(0,10100)


plot <- test.data5 %>%
  select(co) %>%
  distinct() %>%
  mutate(co_range = as.character(co)) %>%
  inner_join(test.data5%>%
               count(co)) %>%
  ggplot(aes(x=co, y = n, fill = as.character(co_range))) + geom_bar(stat='identity') + ylab("count") + xlab("Carbon Monoxide (co)") + scale_x_discrete(labels = function(x) sprintf("%.3f", as.numeric(x))) + ylim(0,9000)

plot <- test.data5 %>%
  select(so2) %>%
  distinct() %>%
  mutate(so2_range = as.character(so2)) %>%
  inner_join(test.data5%>%
               count(so2))%>%
   ggplot(aes(x=so2, y = n, fill = as.character(so2_range))) + geom_bar(stat='identity') + ylab("count") + xlab("Sulfur Dioxide (so2)") + scale_x_discrete(labels = function(x) sprintf("%.3f", as.numeric(x))) + ylim(0,10100)

source("./helper.R")
save_with_theme(apply_theme(plot))

plot <- ggplot(data.frame(sim.data$co), aes(sim.data$co, fill="red")) + geom_histogram(bins = 20) + xlab("Carbon Monoxide (co)")

ggplot(data.frame(sim.data$co), aes(sim.data$co)) + geom_histogram(bins = 2) + xlab("co")

ggplot(data.frame(sim.data$co), aes(sim.data$co)) + geom_density() + xlab("co") + xlim(1.4375,1.445)

(plot <- ggplot(data.frame(sim.data$so2), aes(sim.data$so2)) + geom_density(colour="#10e7d9", size=2) + xlab("Sulfur Dioxide (so2)"))

save_with_theme(apply_theme(ggplot(test.data, aes(x=co)) + geom_bar()))

ggplot(test.data4, aes(x=co)) + geom_bar()

ggplot(test.data5, aes(x=co, color)) + geom_bar() + xlab("Carbon Monoxide (co)")

plot<- ggplot(test.data7, aes(x=co, fill="red")) + geom_bar()+ xlab("Carbon Monoxide (co)")



plot<- ggplot(data.frame(sim.data$so2), aes(sim.data$so2, fill="red")) + geom_histogram(bins = 20) + xlab("Sulfur Dioxide (so2)")

ggplot(data.frame(sim.data$so2), aes(sim.data$so2)) + geom_histogram(bins = 2) + xlab("Sulfur Dioxide (so2)")

ggplot(data.frame(sim.data$so2), aes(sim.data$so2)) + geom_density() + xlab("Sulfur Dioxide (so2)") + xlim(13.76,13.86)

ggplot(data.frame(sim.data$so2), aes(sim.data$so2)) + geom_density() + xlab("Sulfur Dioxide (so2)")

(plot<-ggplot(test.data, aes(x=so2, fill=so2)) + geom_bar() + xlab("Sulfur Dioxide (so2)"))

(plot<-ggplot(test.data, aes(x=co, fill=co)) + geom_bar() + xlab("Carbon Monoxide (co)"))

ggplot(test.data5, aes(x=so2)) + geom_bar()

plot<-ggplot(test.data7, aes(x=so2, fill="red")) + geom_bar() + xlab("Sulfur Dioxide (so2)")

plot<-test.data3 %>%
  select(co) %>%
  distinct() %>%
  add_count(co) %>%
  mutate(p_co = (n / nrow(test.data3))*100) %>%
  select(-n) %>%
  inner_join(test.data3) %>%
  ggplot(aes(x=co, y = p_co, fill=co)) + geom_bar(stat='identity') + ylab("P [%]") + xlab("Carbon Monoxide (co)")


```


```{r}

  f <- test.data %>%
    select(so2, co, Type, Zone, Year) %>%
    #select(so2, co, Type, Zone, DateTime) %>%
    add_count(Zone) %>%
    
    mutate(prob_zone = n / n()) %>%
    select(-n) %>%
    add_count(Type) %>%
    mutate(prob_type = n / n()) %>%
    select(-n) %>%
    #add_count(DateTime) %>%
    add_count(Year) %>%
    mutate(prob_datetime = n / n()) %>%
    select(-n) %>%
    #group_by(Zone, Type, DateTime, co) %>%
    group_by(Zone, Type, Year, co) %>%
    add_count(so2) %>%
    group_by(Zone, Type, Year, co) %>%
    mutate(count = n(),
      so2_cond_prob = n / n()) %>%
    ungroup() %>%
    distinct() %>%
    mutate(total_prob = prob_zone * prob_type * prob_datetime * so2_cond_prob) %>%
    arrange(Type, Zone, Year) 
  
    
    f3 <- test.data %>%
    select(Type, Zone, Year) %>%
    #select(so2, co, Type, Zone, DateTime) %>%
    add_count(Zone) %>%
    
    mutate(prob_zone = n / n()) %>%
    select(-n) %>%
    add_count(Type) %>%
    mutate(prob_type = n / n()) %>%
    select(-n) %>%
    #add_count(DateTime) %>%
    add_count(Year) %>%
    mutate(prob_datetime = n / n()) %>%
    select(-n) %>%
    tidyr::expand(Type, Zone, Year) %>%
      left_join(f %>% select(Type, prob_type) %>% distinct()) %>%
      left_join(f %>% select(Zone, prob_zone) %>% distinct()) %>%
      left_join(f %>% select(Year, prob_datetime) %>% distinct())

```

```{r}

loop.based.function <- function(data, co, so2){
  result <- 0
  for(type in unique(data$Type)){
    for(zone in unique(data$Zone)){
      for(year in unique(data$Year)){
        # print(paste(type, zone, year, sep = "-"))
        r <- sum(data$Type == type & data$Zone == zone & data$Year == year & data$co == co)
        temp = sum(data$Type == type)/ nrow(data) * 
          sum(data$Zone == zone)/ nrow(data) * 
          sum(data$Year == year)/ nrow(data) * 
          sum(data$Type == type & data$Zone == zone & data$Year == year & data$co == co & data$so2 == so2) / if_else(r == 0, 1L, r)
        # print(temp)
        result <- result + temp
      }
    }
  }
  result
}

loop.based.function (test.data, "2", "1")
loop.based.function (test.data, "2", "2")

loop.based.function (test.data, "1", "1")
loop.based.function (test.data, "1", "2")
```

```{r}
so2.2 <- test.data %>% filter(so2 == "2")	

so2.2 %>% select(so2, Type, Zone, Year) %>% distinct()
=
```