---
title: "Investigation of Causal Effects"
author: "Daniel Lindner, Simon Witzke"
date: "6/30/2020"
output: pdf_document
---

```{r setup, include=FALSE}
library(bnlearn)
library(Rgraphviz)
library(tidyverse)
library(causaleffect)
library(igraph)
knitr::opts_chunk$set(tidy.opts=list(width.cutoff=62), tidy=TRUE, message = FALSE, warning = FALSE)
load("./mehra-complete.rda")

# load data
load("./data-johannes-20000.rds")
```

## Translation of learned bayesian network to igraph

```{r warning = FALSE}

# TODO replace bn with our learned and saved model
adj.matrix.from.bngraph <- amat(bn)
igraph.from.bnmatrix<- graph_from_adjacency_matrix(adj.matrix.from.bngraph)
# TODO mark undirected edges as such

```

## Plot network

```{r pressure, echo=FALSE}
graphviz.plot(bn)
```


## Find causal effect
```{r }
effect.igraph.from.bnmatrix <- causal.effect(y = "so2", x = "co", z = NULL, G = igraph.from.bnmatrix, expr = T)
```

$`
```{r echo=FALSE, results="asis"}
cat(effect.igraph.from.bnmatrix)
```
`$

## Estimate causal effect strength

```{r define functions for causal effect}

# generates table with all combinations of so2 and co and the respectice causal effect/ probability
causal.effect.probabilites.so2.co <- function(data) {
  
  # select relevant columns
  data <- data %>%
    select(so2, co, Type, Zone, Year) 
  
  # calculate probabilities for realisations of Zone 
  data <- data %>%
    add_count(Zone) %>%
    mutate(prob_zone = n / n()) %>%
    select(-n) 
  
  # calculate probabilities for realisations of Type 
  data <- data %>%
    add_count(Type) %>%
    mutate(prob_type = n / n()) %>%
    select(-n) 
  
  # calculate probabilities for realisations of Year 
  data <- data %>%
    add_count(Year) %>%
    mutate(prob_datetime = n / n()) %>%
    select(-n) 
  
  # calculate conditional probability for so2 by Zone, Type, Year, co
  data <- data %>%
    group_by(Zone, Type, Year, co) %>%
    add_count(so2) %>%
    group_by(Zone, Type, Year, co) %>%
    mutate(so2_cond_prob = n / n()) %>%
    select(-n) 
  
  # calculate causal effect and add probability for co to table
  data <- data %>%
    ungroup() %>%
    distinct() %>%
    mutate(total_prob = prob_zone * prob_type * prob_datetime * so2_cond_prob) %>%
    group_by(so2, co) %>%
    summarise("P(so2|do(co))" = sum(total_prob)) %>%
    inner_join(data %>%
                 group_by(co) %>%
                 count(co) %>%
                 mutate("P(co)" = n / nrow(data)) %>%
                 select(-n))
  
}

# calculates the conditional mutual information for do(co) on so2
conditional.mutual.information.so2.co <- function(data) {
  causal.effects <- causal.effect.probabilites.so2.co(data)
  
  # Calculation of sum in denominator of logarithm
  log.sum <- function(vj){
    sum(causal.effects %>%
      filter(so2 == vj) %>%
      base::apply(MARGIN = 1, function(x)
      as.numeric(x["P(so2|do(co))"]) * as.numeric(x["P(co)"])))
  }
  
  # Rowwise calculation of Conditional Mutual Information
  sum(causal.effects %>%
        base::apply(MARGIN = 1, function(x)
          as.numeric(x["P(co)"]) * as.numeric(x["P(so2|do(co))"]) * log(as.numeric(x["P(so2|do(co))"]) / log.sum(x["so2"]))))
}

```


```{r define function for causal effect 2}

loop.based.function <- function(data, co, so2){
  result <- 0
  for(type in unique(data$Type)){
    for(zone in unique(data$Zone)){
      for(year in unique(data$Year)){
        # print(paste(type, zone, year, sep = "-"))
        r <- sum(data$Type == type & data$Zone == zone & data$Year == year & data$co == co)
        temp = sum(data$Type == type)/ nrow(data) * 
          sum(data$Zone == zone)/ nrow(data) * 
          sum(data$Year == year)/ nrow(data) * 
          sum(data$Type == type & data$Zone == zone & data$Year == year & data$co == co & data$so2 == so2) / if_else(r == 0, 1L, r)
        # print(temp)
        result <- result + temp
      }
    }
  }
  result
}

```


```{r}
# Exectution of "faster" data.frame based caual effect function
causal.effect.probabilites.so2.co(test.data) %>% arrange(co)

# Exection of conditional mutual information estimation function
conditional.mutual.information.so2.co(test.data)


# Execution of loop-based causal effect function for all combinations of so2 and co
loop.based.function (test.data, "2", "1")
loop.based.function (test.data, "2", "2")

loop.based.function (test.data, "1", "1")
loop.based.function (test.data, "1", "2")
```





```{r}
# verification that so2 = 2 only has very few combinations of Zone, Type, Year (4 combination shown where when year was discretized to 2 realisations)
so2.2 <- test.data %>% filter(so2 == "2")	

so2.2 %>% select(so2, Type, Zone, Year) %>% distinct()

```